---
apiVersion: v1
kind: Service
metadata:
  name: alpha-blog-service
  labels:
    app: alpha-blog
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: alpha-blog
    app.kubernetes.io/name: alpha-blog
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-blog
  labels:
    app: alpha-blog
spec:
  template:
    metadata:
      name: alpha-blog-pod
      labels:
        app.kubernetes.io/instance: alpha-blog
        app.kubernetes.io/name: alpha-blog
    spec:
      containers:
        - name: alpha-blog-container
          image: jimcodified/dockercon2020:alpha-blog.orig

  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: alpha-blog
      app.kubernetes.io/name: alpha-blog    
